# Generated by Django 2.2.2 on 2020-05-19 09:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен в обработку'), ('PD', 'оплачен'), ('PRD', 'обрабатывается'), ('RDY', 'готов'), ('CNC', 'отменен')], default='FM', max_length=3, verbose_name='статус')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Template's name")),
                ('price', models.PositiveIntegerField()),
                ('orders', models.PositiveIntegerField(default=0)),
                ('banner', models.ImageField(upload_to='', verbose_name="Template's Image")),
                ('path', models.CharField(default='media/projects/...', max_length=200, verbose_name='Path to template')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=9, null=True, unique=True)),
                ('url', models.CharField(max_length=100, null=True, unique=True)),
                ('date_of_expiry', models.DateField(default=datetime.datetime(2021, 5, 19, 12, 28, 47, 208342))),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Hotel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor_app.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor_app.Template'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
