# Generated by Django 2.2.2 on 2020-06-06 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0004_auto_20200606_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 20, 52, 6, 151077)),
        ),
    ]
