# Generated by Django 2.2.2 on 2020-06-07 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0008_auto_20200607_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='date_of_expiry',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 17, 12, 44, 405962)),
        ),
    ]
